repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: name-tests-test
  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: mypy-producer
        name: mypy-producer
        entry: mypy producer/src
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
      - id: mypy-consumer
        name: mypy-consumer
        entry: mypy consumer/src
        language: system
        types: [python]
        pass_filenames: false
        always_run: true