repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
  - repo: https://github.com/python-poetry/poetry
    rev: 1.7.0
    hooks:
      - id: poetry-check
        name: poetry check producer
        args: ["-C", "./producer"]
      - id: poetry-lock
        name: poetry lock producer
        args: ["-C", "./producer"]
      - id: poetry-export
        name: poetry export producer dev dependencies
        args: [
          "-C",
          "./producer",
          "-f", "requirements.txt",
          "-o",
          "./producer/requirements-dev.txt",
          "--without-hashes",
          "--with",
          "dev"
        ]
        always_run: true
      - id: poetry-export
        name: poetry export producer dependencies
        args: [
          "-C",
          "./producer",
          "-f", "requirements.txt",
          "-o",
          "./producer/requirements.txt",
          "--without-hashes"
        ]
        always_run: true
      - id: poetry-check
        name: poetry check consumer
        args: ["-C", "./consumer"]
      - id: poetry-lock
        name: poetry lock consumer
        args: ["-C", "./consumer"]
      - id: poetry-export
        name: poetry export consumer dev dependencies
        args: [
          "-C",
          "./consumer",
          "-f", "requirements.txt",
          "-o",
          "./consumer/requirements-dev.txt",
          "--without-hashes",
          "--with",
          "dev"
        ]
        always_run: true
      - id: poetry-export
        name: poetry export consumer dependencies
        args: [
          "-C",
          "./consumer",
          "-f", "requirements.txt",
          "-o",
          "./consumer/requirements.txt",
          "--without-hashes"
        ]
        always_run: true
