version: '3.8'
services:
  records_postgres:
    image: records_postgres:${POSTGRES_VERSION_TAG}
    container_name: records_postgres
    build:
      context: database
      dockerfile: dockerfile
      args:
        POSTGRES_VERSION_TAG: ${POSTGRES_VERSION_TAG}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:5432
    restart: always
  records_rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION_TAG}
    container_name: records_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - ${RABBITMQ_WEBAPP_PORT}:15672
      - ${RABBITMQ_PORT}:5672
    restart: always
